apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    component: backend
spec:
  containers:
    - name: simple-app
      image: adarshaug/simple-app
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 31515
  selector:
    component: backend